	db "MASTER BALL@"
	db "HYPER BALL@"
	db "POUDRE CLAIRE@"
	db "SUPER BALL@"
	db "# BALL@"
	db "HONOR BALL@"
	db "BICYCLETTE@"
	db "PIERRE LUNE@"
	db "ANTIDOTE@"
	db "ANTI-BRULE@"
	db "ANTIGEL@"
	db "REVEIL@"
	db "ANTI-PARA@"
	db "GUERISON@"
	db "POTION MAX@"
	db "HYPER POTION@"
	db "SUPER POTION@"
	db "POTION@"
	db "CORDE SORTIE@"
	db "REPOUSSE@"
	db "MAX ELIXIR@"
	db "PIERRE FEU@"
	db "PIERRE FOUDRE@"
	db "PIERRE EAU@"
	db "POISON GUARD@" ;TODO: incorrect (n'existe manifestement pas)
	db "PV PLUS@"
	db "PROTEINE@"
	db "FER@"
	db "CARBONE@"
	db "POING CHANCE@"
	db "CALCIUM@"
	db "SUPER BONBON@"
	db "PRECISION +@"
	db "PIERRE PLANTE@"
	db "POUDRE METAL@"
	db "PEPITE@"
	db "# POUPEE@"
	db "TOTAL SOIN@"
	db "RAPPEL@"
	db "RAPPEL MAX@"
	db "DEFENSE SPEC@"
	db "SUPEREPOUSSE@"
	db "MAX REPOUSSE@"
	db "MUSCLE +@"
	db "BURN GUARD@" ;TODO: incorrect (n'existe manifestement pas)
	db "EAU FRAICHE@"
	db "SODA COOL@"
	db "LIMONADE@"
	db "ATTAQUE +@"
	db "FREEZE GUARD@" ;TODO: incorrect (n'existe manifestement pas)
	db "DEFENSE +@"
	db "VITESSE +@"
	db "SPECIAL +@"
	db "BOITE JETONS@"
	db "CHERCH'OBJET@"
	db "# FLUTE@"
	db "MULTI EXP@"
	db "CANNE@"
	db "SUPER CANNE@"
	db "FEUILLE ARG.@"
	db "MEGA CANNE@"
	db "PP PLUS@"
	db "HUILE@"
	db "HUILE MAX@"
	db "ELIXIR@"
	db "ECAILLEROUGE@"
	db "POTIONSECRET@"
	db "PASSE BATEAU@"
	db "OEUF MYSTERE@"
	db "GLAS TRANSPARENT@"
	db "ARGENT'AILE@"
	db "LAIT MEUMEU@"
	db "VIVE GRIFFE@"
	db "BAIE PECHA@"
	db "FEUILLE D'OR@"
	db "SABLE DOUX@"
	db "BEC POINTU@"
	db "BAIE CERIZ@"
	db "BAIE WILLIA@"
	db "BAIE FRAIVE@"
	db "PIC VENIN@"
	db "ROCHE ROYALE@"
	db "BAIE KIKA@"
	db "BAIE MARON@"
	db "NOIGRUME RGE@"
	db "PETIT CHAMPI@"
	db "GROS CHAMPI@"
	db "POUDRE ARGENTEE@"
	db "NOIGRUME BLU@"
	db "SLEEP GUARD@";TODO: incorrect (n'existe manifestement pas)
	db "PIECE RUNE@"
	db "NOIGRUME JNE@"
	db "NOIGRUME VER@"
	db "RUNE PURIFIANTE@"
	db "EAU MYSTIQUE@"
	db "CUILLER TORDUE@"
	db "NOIGRUME BLC@"
	db "CEINTURE NOIRE@"
	db "NOIGRUME NOI@"
	db "PARLYZ GUARD@";TODO: incorrect (n'existe manifestement pas)
	db "NOIGRUME ROS@"
	db "LUNETTES NOIRES@"
	db "QUEUERAMOLOS@"
	db "RUBAN ROSE@"
	db "BATON@"
	db "BOULE FUMEE@"
	db "GLACE ETERNELLE@"
	db "AIMANT@"
	db "BAIE PRINE@"
	db "PERLE@"
	db "GRANDE PERLE@"
	db "PIERRE STASE@"
	db "RUNE SORT@"
	db "BONBON RAGE@"
	db "GS BALL@"
	db "CARTE BLEUE@"
	db "GRAIN MIRACLE@"
	db "MASSE OS@"
	db "BANDEAU@"
	db "CONFUSEGUARD@" ;TODO: incorrect (n'existe manifestement pas)
	db "POUDRENERGIE@"
	db "RACINENERGIE@"
	db "POUDRE SOIN@"
	db "HERBE RAPPEL@"
	db "PIERRE DURE@"
	db "OEUF CHANCE@"
	db "CLE MAGNETIQUE@"
	db "PIECE MECA.@"
	db "TICKET OEUF@"
	db "POUPEE PERDUE@"
	db "POUSSIERE ETOILE@"
	db "MORCEAU D'ETOILE@"
	db "CLE SOUS-SOL@"
	db "PASSE TRAIN@"
	db "FOSSILE NAUTILE@"
	db "FOSSILE DOME@"
	db "VIEIL AMBRE@"
	db "CHARBON@"
	db "JUS DE BAIE@"
	db "LENTILSCOPE@"
	db "COLIS CHEN@"
	db "HERBE POUVOIR@"
	db "PEAU METAL@"
	db "CROC DRAGON@"
	db "FRIEND CHARM@" ;TODO: incorrect (n'existe manifestement pas)
	db "RESTES@"
	db "NOTE RECHERCHE@"
	db "TERU-SAMA@"
	db "TERU-SAMA@"
	db "BAIE MEPO@"
	db "ECAILLE DRACO@"
	db "ADN BERZERK@"
	db "TERU-SAMA@"
	db "DEF. SPE. +@"
	db "TERU-SAMA@"
	db "CENDRESACREE@"
	db "MASSE BALL@"
	db "LETTRE FLEUR@"
	db "NIVEAU BALL@"
	db "APPAT BALL@"
	db "SPEED BALL@"
	db "TERU-SAMA@"
	db "BALLELUMIERE@"
	db "COPAIN BALL@"
	db "LUNE BALL@"
	db "LOVE BALL@"
	db "COFFRE NORMAL@"
	db "COFFRE LUXE@"
	db "PIERRE SOLEIL@"
	db "RUBAN A POIS@"
	db "TERU-SAMA@"
	db "AMELIORATOR@"
	db "BAIE ORAN@"
	db "BAIE SITRUS@"
	db "CARAPUCE A O@"
	db "TERU-SAMA@"
	db "PARC BALL@"
	db "ARCENCI'AILE@"
	db "TERU-SAMA@"
	db "MORC.@"
	db "LETTRE SURF@"
	db "LETRBLEUCIEL@"
	db "LETRPORTRAIT@"
	db "LETRCHARM.@"
	db "LETTRE EVOLI@"
	db "LETTRE MORPH@"
	db "LETRCIELBLEU@"
	db "LETTRE MUSIQUE@"
	db "LETTRE MIRAGE@"
	db "TERU-SAMA@"
	db "CT01@"
	db "CT02@"
	db "CT03@"
	db "CT04@"
	db "TERU-SAMA@"
	db "CT05@"
	db "CT06@"
	db "CT07@"
	db "CT08@"
	db "CT09@"
	db "CT10@"
	db "CT11@"
	db "CT12@"
	db "CT13@"
	db "CT14@"
	db "CT15@"
	db "CT16@"
	db "CT17@"
	db "CT18@"
	db "CT19@"
	db "CT20@"
	db "CT21@"
	db "CT22@"
	db "CT23@"
	db "CT24@"
	db "CT25@"
	db "CT26@"
	db "CT27@"
	db "CT28@"
	db "TERU-SAMA@"
	db "CT29@"
	db "CT30@"
	db "CT31@"
	db "CT32@"
	db "CT33@"
	db "CT34@"
	db "CT35@"
	db "CT36@"
	db "CT37@"
	db "CT38@"
	db "CT39@"
	db "CT40@"
	db "CT41@"
	db "CT42@"
	db "CT43@"
	db "CT44@"
	db "CT45@"
	db "CT46@"
	db "CT47@"
	db "CT48@"
	db "CT49@"
	db "CT50@"
	db "CS01@"
	db "CS02@"
	db "CS03@"
	db "CS04@"
	db "CS05@"
	db "CS06@"
	db "CS07@"
	db "TERU-SAMA@"
	db "TERU-SAMA@"
	db "TERU-SAMA@"
	db "TERU-SAMA@"
	db "TERU-SAMA@"
	db "TERU-SAMA@"
	db "?@"
